unalias run-help 2>/dev/null || true
autoload run-help

# Set help directory based on OS
if [[ "$OSTYPE" == "darwin"* ]]; then
    HELPDIR=/usr/local/share/zsh/helpfiles
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Common locations on Linux
    if [[ -d /usr/share/zsh/help ]]; then
        HELPDIR=/usr/share/zsh/help
    elif [[ -d /usr/share/zsh/*/help ]]; then
        HELPDIR=/usr/share/zsh/*/help
    fi
fi

LC_CTYPE=en_US.UTF-8

if [ -z "$LOCAL_ZSHRC" ]; then
    LOCAL_ZSHRC=$HOME/.zshrc_local
fi

# Add completions based on OS
if [[ "$OSTYPE" == "darwin"* ]]; then
    [[ -d /usr/local/share/zsh-completions ]] && fpath=(/usr/local/share/zsh-completions $fpath)
    [[ -d /opt/homebrew/share/zsh-completions ]] && fpath=(/opt/homebrew/share/zsh-completions $fpath)
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    [[ -d /usr/share/zsh/vendor-completions ]] && fpath=(/usr/share/zsh/vendor-completions $fpath)
    [[ -d /usr/local/share/zsh-completions ]] && fpath=(/usr/local/share/zsh-completions $fpath)
fi

# Initialize Homebrew if available (macOS only)
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [[ -x /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x /usr/local/bin/brew ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
test -e "$HOME/.cargo/bin" && export PATH="$HOME/.cargo/bin:$PATH"

if command -v mise &>/dev/null; then
    eval "$(mise activate zsh)"
else
    command -v nodenv &>/dev/null && eval "$(nodenv init - zsh)"
    if command -v pyenv &>/dev/null; then
        eval "$(pyenv init --path zsh)"
        alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'
    fi
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
if [ -n "$INSIDE_EMACS" ]; then
   ZSH_THEME="steeef"
else
   # ZSH_THEME="agnoster"
   command -v starship &>/dev/null && eval "$(starship init zsh)"
fi

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# Base plugins for all platforms
plugins=(
    # aws
    # git
    github
    mise
    mosh
    npm
    pip
    rust
)

# Add direnv plugin only if direnv is installed
if command -v direnv &>/dev/null; then
    plugins+=(direnv)
fi

# Add OS-specific plugins
if [[ "$OSTYPE" == "darwin"* ]]; then
    plugins+=(macos)
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Add Linux-specific plugins if needed
    # plugins+=(ubuntu debian archlinux)
    :
fi

source $ZSH/oh-my-zsh.sh

# export ZPLUG_HOME=/usr/local/opt/zplug
# source $ZPLUG_HOME/init.zsh

# zplug load --verbose

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Customize to your needs...
if [[ -e "$LOCAL_ZSHRC" ]]; then
    source "$LOCAL_ZSHRC"
fi
